[package]
name = "arbor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.4"
rapier2d ="0.17.2"
nalgebra ="0.32.3"
glam ="0.24.1"
wasm-timer="0.2.5"
ecs_rust = "0.0.4"
